export { default as Hero } from "./hero/Hero"
export { default as About } from "./about/About"
export { default as Skills } from "./skills/Skill"
export { default as Projects } from "./projects/Projects"
export { default as Contact } from "./contact/Contact"